-- CreateEnum
CREATE TYPE "Impact" AS ENUM ('NO_POVERTY', 'ZERO_HUNGER', 'GOOD_HEALTH_AND_WELL_BEING', 'QUALITY_EDUCATION', 'GENDER_EQUALITY', 'CLEAN_WATER_AND_SANITATION', 'AFFORDABLE_AND_CLEAN_ENERGY', 'DECENT_WORK_AND_ECONOMIC_GROWTH', 'INDUSTRY_INNOVATION_AND_INFRASTRUCTURE', 'REDUCED_INEQUALITIES', 'SUSTAINABLE_CITIES_AND_COMMUNITIES', 'RESPONSIBLE_CONSUMPTION_AND_PRODUCTION', 'CLIMATE_ACTION', 'LIFE_BELOW_WATER', 'LIFE_ON_LAND', 'PEACE_JUSTICE_AND_STRONG_INSTITUTIONS', 'PARTNERSHIPS_FOR_THE_GOALS');

-- CreateEnum
CREATE TYPE "Status" AS ENUM ('ON_GOING', 'ACHIEVED', 'CLOSED');

-- CreateTable
CREATE TABLE "donations" (
    "id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "status" "Status" NOT NULL,
    "goal" INTEGER NOT NULL,
    "owners" TEXT[],
    "impacts" "Impact"[],

    CONSTRAINT "donations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Donation" (
    "id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "amount" INTEGER NOT NULL,
    "projectId" TEXT NOT NULL,

    CONSTRAINT "Donation_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Donation_email_key" ON "Donation"("email");

-- AddForeignKey
ALTER TABLE "Donation" ADD CONSTRAINT "Donation_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "donations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

